[[redirects]]
  from = "/positions.json/*"
  to = "https://jobs.github.com/positions.json/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/job/:id.json"
  to = "https://jobs.github.com/positions/:id.json"
  status = 200
  force = true
